name: GitHub Actions - Teste com dependencia Template
run-name: Running -  Teste com dependencia Template
on: [push, workflow_dispatch]
jobs:
   test-unit:
     runs-on: ubuntu-latest
     steps:
       - name: Comentario
         run: |
           echo "Execucao Unit"
   test-api:
     #needs: test-unit
     runs-on: ubuntu-latest
     steps:
       - name: Comentario
         run: |
           echo "Execucao API"   
   test-ui:
     needs: [test-unit, test-api]
     runs-on: ubuntu-latest
     steps:
       - name: Comentario
         run: |
           echo "Execucao UI"   