name: GitHub Actions - Matrix Strategy Template
run-name: Running -  Matrix Strategy Template
on: [push, workflow_dispatch]
jobs:
   matrix_job:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         navegador: [chrome, firefox, webkit]
         tag: [tag_1, tag_2, tag_3]
         framework: [robot, cypress, selenium]
       fail-fast: false
     steps:
       - name: Comentario
         run: |
           echo "${{ matrix.navegador }}"
           echo "${{ matrix.tag }}"
