name: GitHub Actions _ Workflow dispatch Template Basico
run-name: Running - ${{ github.event_name }}
on: [workflow_dispatch]
jobs:
  on_workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentario workflow dispatch - Basic"