name: GitHub Actions _ Workflow dispatch Template - String
run-name: Running - ${{ github.event_name }}
on: 
    workflow_dispatch:
      inputs:
        browser:
          description: Selecione o Browser 
          type: string
jobs:
  on_workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentario workflow dispatch - Browser ${{ inputs.browser }}"