name: GitHub Actions _ Workflow dispatch Template - Booleano
run-name: Running - ${{ github.event_name }}
on: 
    workflow_dispatch:
      inputs:
        severidade:
          description: funcionalidade critica?
          type: boolean
jobs:
  on_workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentario workflow dispatch - Boolean: ${{ inputs.severidade }}"