name: GitHub Actions - Condiguracao de Secret de repositorio
run-name: Running -  Secret Repo COnfig
on: [push, workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "${{ secrets.test_secret }}"
