name: Github Action - Push - Branch Template
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentario
        run: |
          echo "Comentario PUSH WORKSFLOW - branch"