name: GitHub Actions - Condicionais
run-name: Running - ${{ github.event_name }}
on: [push, workflow_dispatch]
jobs:
  on_push_only:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo ${{ github.event_name }}
  on_workflow_dispatch_only:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo ${{ github.event_name }}