name: Github Action - Pull - Branch Template
run-name: Running - ${{ github.event_name }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentario PULL REQUEST WORKSFLOW - branch"