name: GitHub Actions - Gerenciamento de erros
run-name: Running - Gerenciamento de erros
on: [push, workflow_dispatch]
jobs:
  job_1_erro:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo Comentario antes do erro
          exit 1
      - name: Comentario
        run: |
          echo Comentario após do erro
  job_2_always:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo Comentario antes do erro
          exit 1
      - name: Comentario
        if: always()
        run: |
          echo Comentario após do erro
  