name: Github Action - Push - Path Template
run-name: Running - ${{ github.event_name }}
on:
  push:
    paths:
      - '**.txt'
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentario PUSH WORKSFLOW - Path"